baseURL: "https://rickybeamer.me"
languageCode: "en-us"
title: "Ricky Beamer's CV"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

enableRobotsTXT: false

pagination:
  pagerSize: 3

markup:
  goldmark:
    renderer:
      unsafe: true

params:
  title: "Hello, I'm Ricky"
  description: This is a GitHub Pages website for my CV.
  favicon: "/images/fav.png"

  useBootstrapCDN: false
  mathjax: false
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    brandName: "Ricky Beamer" # Brand name for the brand | default is the title variable
    disableSearch: true
    stickyNavBar:
      enable : true
      showOnScrollUp : true
    enableSeparator: true
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Ricky."
    subtitle: "Systems Engineer SME"
    content: "Highly experienced Systems Engineer with a strong foundation in Aerospace and Mechanical engineering, complemented by extensive computer science expertise and over 10 years specializing in the analysis, safety, and testing of critical human spaceflight software."
    image: /images/header.jpg
    bottomImage:
      enable: true
      roundImage: false # Make hero image circular | default false
    button:
      enable: true
      name: "Curriculum Vitae"
      url: "/images/CV.pdf"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/rb6
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/fbeamer/

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/me.png"
    content: |-
      Systems Engineer trained in Aerospace and Mechanical Engineering with an extensive computer science background. Over 10 years of experience in analyzing complex systems focusing on safety and mission critical human space flight software. Additional expertise in research, design, and execution of dynamic test cases for spacecraft flight software utilizing advanced simulation software packages. I am currently working as a Systems Engineer SME at [KLS Government Services](https://www.kls-llc.com/) contracted to NASA's [Independent Verification and Validation (IV&V) program](https://www.nasa.gov/katherine-johnson-ivv-facility/) in Fairmont, WV.

    skills:
      enable: true
      title: "Areas of Expertise"
      items:
        - "System & Software Assurance"
        - "Python"
        - "C++"
        - "Software Safety"
        - "Software Testing"
        - "Safety & Mission Assurance"
        - "Visual Basic"
        - "MATLAB"
        - "Linux"
        - "Photography"
        - "Software Quality"
        - "Raspberry Pi"
        - "IP Networking"
        - "MS Windows"
        - "Microsoft Office"
        - "Rocketry"

  # Experience
  experience:
    enable: true
    items:
      - job: "Systems Engineer SME"
        company: "KLS Government Services"
        companyUrl: "https://www.kls-llc.com/"
        date: "May 2012 - present"
        info:
          enable: true
          content: More than 10 years of experience as a Systems Engineer.
        content: |
          - Contracted to NASA's Independent Verification and Validation (IV&V) program focusing on safety and mission critical human spaceflight software
          - Research, design, and execute dynamic test cases for spacecraft flight and ground software utilizing advanced simulation software packages
          - Transitioned to the IV&V Artemis Test Team in Spring 2020
          - Testing focused on examining critical functions necessary across Orion, Space Launch System (SLS), and Exploration Ground System (EGS) programs in support of planned Artemis missions
          - Testing focus includes:
            - Ascent guidance targeting
            - Ascent abort scenarios
            - Earth Orbit Operations and Orion Vehicle Checkout
            - Service Module Fairing failures and recovery operations
          - Previously the IV&V Orion dynamic testing team lead from Fall 2013 until Spring 2020
          - Evaluated software requirements from definition through implementation and testing. Domain experience in:
            - Timeline and Vehicle Management (TVM)
            - Environmental Control and Life Support (ECLS)
            - Guidance, Navigation, Control and Propulsion (GNCP)
          - Analyzed software developed under Agile and Waterfall software development models
          - Mentored four year-long interns with projects involving the full lifecycle dynamic test process including test case proposal, script development, run-for-record testing, and closeout reports and determining the fedelity of the models utilized within the testing simulation environment
          - Mentored several summer college and high school interns. Responsible for ensuring interns become familiar with the available testing enviornments, conduct test following the proper procedures, and confirming that the results generated are appropriate for current and future analysis and planning. Projects involved:
            - Dynamic testing environment setup and configuration
            - Creation of custom tools for use by other IV&V Orion system engineers and IV&V personnel
            - Comparing software development test envirponments to certified testing enviornments
            - Development of test cases to recreate flight scenarios investigating inflight anomalies

      - job: "Graduate Teaching Assistant, Aircraft Health Manageent Class"
        company: "West Virginia University"
        companyUrl: "https://www.statler.wvu.edu/"
        date: "Aug 2011 - Dec 2011"
        info:
          enable: false
        content: |
          - Assisted the professor and students during laboratory experiments by providing guidance in experiment design and analysis
          - Introduced perspective high school and freshmen engineering students to aircraft simulators and the aircraft health manangement class through interactive information sessions
          - Oversaw the operation of the 6-degree-of-freedom (6DOF) flight simulator and PC based simulators

      - job: "Graduate Research Assistant"
        company: "West Virginia University"
        companyUrl: "https://www.statler.wvu.edu/"
        date: "Jan 2010 - Aug 2011"
        info:
          enable: false
        content: |
          - Contributed to the development of an undergraduate and graduate level course in Aircraft Health Managemen
          - Developed new aircraft models and retrofitted/upgraded existing models within MATLAB and Simulink
          - Managed the software upgrade from MATLAB 6.5 to MATLAB 2011a (version 7.12) including updating and evaluating specific sofware packages used for the Aircraft Health Management courses
          - Supervised the operation of the 6DOF flight simulator nd PC-based simulators

  # Education
  education:
    enable: true
    index: false
    items:
      - title: "Master of Science in Aerospace Engineering"
        school:
          name: "West Virginia University"
          url: "https://www.statler.wvu.edu/"
        date: "2009 - 2011"
        GPA: "3.6 out of 4.0"
        content: |
          - Thesis: [Analysis of Aircraft Multiple Engine Configurations for Fault Tolerant Control](https://researchrepository.wvu.edu/etd/2295/)
          - Key Courses
            - Applied Linear Algebra
            - Numerical Analysis
            - Advanced Thermodynamics
            - AI Techniques for Engineering
            - Feedback Control in Mechanical Engineering
            - Aircraft Health Management
        featuredLink:
          enable: false

      - title: "Bachelor of Science in Aerospace Engineering"
        school:
          name: "West Virginia University"
          url: "https://www.statler.wvu.edu/"
        date: "2004 - 2008"
        GPA: "3.28 out of 4.0"
        content: |-
          - Key Courses
            - Mechatronics
            - Thermodynamics
            - Analysis of Engineering Systems (Numerical Analysis)
            - Incompressible and Compressible Aerodynamics
            - Heat Transfer
            - Aerospace Structures
            - Flight Dynamics
            - Flight Vehicle Propulsion
            - Experimental Aerodynamics
            - Flight Vehicle Design
            - Computational Fluid Dynamics (CFD)
            - Space Flight and Systems
            - Guided Missile Systems
        featuredLink:
          enable: false

      - title: "Bachelor of Science in Mechanical Engineering"
        school:
          name: "West Virginia University"
          url: "https://www.statler.wvu.edu/"
        date: "2004 - 2008"
        GPA: "3.28 out of 4.0"
        content: |-
          - Key Courses
            - Statics, Dynamics, and Mechanics of Materials
            - Mechatronics
            - Mechanics of Materials
            - Thermodynamics
            - Heat Transfer
            - Analysis of Engineering Systems
            - Dynamics of Machines
            - Manufacturing Processes
            - Internal Combustion Engines
            - Automatic Controls
            - Computer Aided Design (CAD) and Finite Element Analysis (FEA)
            - Engineering Economy
            - Machine Design and Manufacturing
        featuredLink:
          enable: false

      - title: "High School"
        school:
          name: "George Wythe High School"
          url: "https://gwhs.wythe.k12.va.us/"

      - title: "Governor's School"
        school:
          name: "Southwest Virginia Governor's School"
          url: "https://www.swvgs.us/"
        content: |
          - SWVGS is a shared-time program; students attend the Governor's School in the morning and return to their home high schools for afternoon classes.
          - Students take math, science, technology, research, study skills, and career education classes at SWVGS.

  # Achievements
  achievements:
    enable: true
    title: "Awards, Professional Presentations, and Publications"
    items:
      - title: Project Achievement Award
        content: In recognition of contributions in support of Artemis I Issue Burndown (11/2021)

      - title: Excellence in Values Award
        content: For demonstration of excellence in support of a successful virtual internship program (11/2021)

      - title: NASA IV&V SAS Program Team Award
        content: For contributing to the growth and advancement of the future innovators, leaders, and architects of NASA's future (8/2019)

      - title: Excellence in Values Award
        content: For teamwork in reorganizing the Orion IV&V team Confluence site, resulting in the restructuring and cleanup of a tremendous amount of information that it contained, making it more useful and usable (12/2018)

      - title: Excellence in Values Award
        content: For contributions in the implementation of A-SCAN into the Orion IV&V team (12/2018)

      - title: Excellence in Values Award
        content: For contributions in support of the Orion IV&V Entry, Descent, and Landing (EDL) Scrum Team during the familiarization of various aspects of the Guidance, Navigation, Control, and Propulsion (GNCP) domain (6/2017)

      - title: Excellence in Values Award
        content: In recognition of contributions in the advancement of MPCV Independent Testing (12/2014)

      - title: Project Achievement Award
        content: In recognition of contributions to the 2013 Combined Federal Campaign Fund Raising Event Efforts (12/2013)

      - title: Excellence in Values Award
        content: In recognition of contributions to the MPCV Test Campaign (6/2013)

      - title: Project Achievement Award
        content: In recognition of contributions to MPCV FSW Test Technical Team (2/2013)

      - title: 2014 Annual Workshop on Verification and Validation
        content: Comparison of IV&V's Use of Non Verification Environments and Program Use of Verification Environments (Presentation)
        url: "https://youtu.be/8XPagSS8Vts"

      - title: 2013 Annual Workshop on Verification and Validation
        content: MPCV IV&V with a Dynamic Twist (Presentation)
        url: "https://youtu.be/tqK_p3VJ7no"

      - title: 2012 Annual Workshop on Verification and Validation
        content: IV&V Dynamic Test and Analysis of the Orion Multi-Purpose Crew Vehicle FSW (Presentation)

      - title: 2011 American Institute of Aeronautics and Astronautics Guidance, Navigation, and Control Conference
        content: Analysis of Aircraft Multiple Engine Configurations for Fault Tolerant Control (AIAA-2011-6407) (Presentation)

      - title: 2011 American Institute of Aeronautics and Astronautics Atmospheric Flight Mechanics Conference
        content: Development of a Simulation Environment to Support Aircraft Health Management Education (AIAA-2011-6614) (Presentation)

      - title: Publication
        content: Perhinschi, M.G., Beamer, F., 2012, Flight Simulation Environment for Undergraduate Education in Aircraft Health Management, Computers in Education Journal, 22 (3)

  # projects
  projects:
    enable: true
    title: "Certificates, Licenses, and Professional Organizations"
    items:
      - title: NASA STEP Level 1 Certificate
        content: NASA Safety and Mission Assurance Technical Excellence Program (STEP) Level 1 Certificate

      - title: Engineer Intern
        content: "Engineer Intern in West Virginia, #8956"

      - title: Private Pilot
        content: Private Pilot, Single Engine Land

      - title: NAR Level 2
        content: National Association of Rocketry (NAR) High Power Rocketry Certified Level 2

      - title: NAR Member
        content: National Association of Rocketry (NAR) Member Number 77933

      - title: NESA
        content: National Eagle Scout Association Member

  #Contact
  contact:
    enable: true
    content: My inbox is always open. Whether you have a question or just want to say hi, Iâ€™ll try my best to get back to you!
    btnName: Mail me
    btnLink: mailto:ricky.beamer+cv@gmail.com

  footer:
    recentPosts:
      enable: false
    socialNetworks:
      github: https://github.com/rb6
      linkedin: https://www.linkedin.com/in/fbeamer/

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    socialShare: true
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true
    tags:
      openInNewTab: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>
